/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class Fields {
	private java.lang.String day_low;

 	public void setDay_low(java.lang.String day_low) {
		this.day_low = day_low;
	}

	public java.lang.String getDay_low() {
		return day_low;
	}

	private java.lang.String day_high;

 	public void setDay_high(java.lang.String day_high) {
		this.day_high = day_high;
	}

	public java.lang.String getDay_high() {
		return day_high;
	}

	private java.lang.String type;

 	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getType() {
		return type;
	}

	private java.lang.String issuer_name_lang;

 	public void setIssuer_name_lang(java.lang.String issuer_name_lang) {
		this.issuer_name_lang = issuer_name_lang;
	}

	public java.lang.String getIssuer_name_lang() {
		return issuer_name_lang;
	}

	private java.lang.String issuer_name;

 	public void setIssuer_name(java.lang.String issuer_name) {
		this.issuer_name = issuer_name;
	}

	public java.lang.String getIssuer_name() {
		return issuer_name;
	}

	private java.lang.String symbol;

 	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public java.lang.String getSymbol() {
		return symbol;
	}

	private java.lang.String ts;

 	public void setTs(java.lang.String ts) {
		this.ts = ts;
	}

	public java.lang.String getTs() {
		return ts;
	}

	private java.lang.String change;

 	public void setChange(java.lang.String change) {
		this.change = change;
	}

	public java.lang.String getChange() {
		return change;
	}

	private java.lang.String volume;

 	public void setVolume(java.lang.String volume) {
		this.volume = volume;
	}

	public java.lang.String getVolume() {
		return volume;
	}

	private java.lang.String year_low;

 	public void setYear_low(java.lang.String year_low) {
		this.year_low = year_low;
	}

	public java.lang.String getYear_low() {
		return year_low;
	}

	private java.lang.String chg_percent;

 	public void setChg_percent(java.lang.String chg_percent) {
		this.chg_percent = chg_percent;
	}

	public java.lang.String getChg_percent() {
		return chg_percent;
	}

	private java.lang.String year_high;

 	public void setYear_high(java.lang.String year_high) {
		this.year_high = year_high;
	}

	public java.lang.String getYear_high() {
		return year_high;
	}

	private java.lang.String price;

 	public void setPrice(java.lang.String price) {
		this.price = price;
	}

	public java.lang.String getPrice() {
		return price;
	}

	private java.lang.String utctime;

 	public void setUtctime(java.lang.String utctime) {
		this.utctime = utctime;
	}

	public java.lang.String getUtctime() {
		return utctime;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}