/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class List {
	private Meta meta;

 	public void setMeta(Meta meta) {
		this.meta = meta;
	}

	public Meta getMeta() {
		return meta;
	}

	private ResourceElement[] resources;

 	public void setResources(ResourceElement[] resources) {
		this.resources = resources;
	}

	public ResourceElement[] getResources() {
		return resources;
	}

}