/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class Meta {
	private java.lang.String type;

 	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getType() {
		return type;
	}

	private java.lang.Integer start;

 	public void setStart(java.lang.Integer start) {
		this.start = start;
	}

	public java.lang.Integer getStart() {
		return start;
	}

	private java.lang.Integer count;

 	public void setCount(java.lang.Integer count) {
		this.count = count;
	}

	public java.lang.Integer getCount() {
		return count;
	}

}