/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class ResourceElement {
	private Resource resource;

 	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public Resource getResource() {
		return resource;
	}

}