/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class Resource {
	private Fields fields;

 	public void setFields(Fields fields) {
		this.fields = fields;
	}

	public Fields getFields() {
		return fields;
	}

	private java.lang.String classname;

 	public void setClassname(java.lang.String classname) {
		this.classname = classname;
	}

	public java.lang.String getClassname() {
		return classname;
	}

}