/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs;

public class YahooStockQuote {
	private List list;

 	public void setList(List list) {
		this.list = list;
	}

	public List getList() {
		return list;
	}

}