/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.amdocs.stock;

public class GoogleQuote {
	private java.lang.String cp_fix;

 	public void setCp_fix(java.lang.String cp_fix) {
		this.cp_fix = cp_fix;
	}

	public java.lang.String getCp_fix() {
		return cp_fix;
	}

	private java.lang.String lt;

 	public void setLt(java.lang.String lt) {
		this.lt = lt;
	}

	public java.lang.String getLt() {
		return lt;
	}

	private java.lang.String l;

 	public void setL(java.lang.String l) {
		this.l = l;
	}

	public java.lang.String getL() {
		return l;
	}

	private java.lang.String ltt;

 	public void setLtt(java.lang.String ltt) {
		this.ltt = ltt;
	}

	public java.lang.String getLtt() {
		return ltt;
	}

	private java.lang.String e;

 	public void setE(java.lang.String e) {
		this.e = e;
	}

	public java.lang.String getE() {
		return e;
	}

	private java.lang.String pcls_fix;

 	public void setPcls_fix(java.lang.String pcls_fix) {
		this.pcls_fix = pcls_fix;
	}

	public java.lang.String getPcls_fix() {
		return pcls_fix;
	}

	private java.lang.String l_fix;

 	public void setL_fix(java.lang.String l_fix) {
		this.l_fix = l_fix;
	}

	public java.lang.String getL_fix() {
		return l_fix;
	}

	private java.lang.String c;

 	public void setC(java.lang.String c) {
		this.c = c;
	}

	public java.lang.String getC() {
		return c;
	}

	private java.lang.String ccol;

 	public void setCcol(java.lang.String ccol) {
		this.ccol = ccol;
	}

	public java.lang.String getCcol() {
		return ccol;
	}

	private java.lang.String id;

 	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	private java.lang.String cp;

 	public void setCp(java.lang.String cp) {
		this.cp = cp;
	}

	public java.lang.String getCp() {
		return cp;
	}

	private java.lang.String t;

 	public void setT(java.lang.String t) {
		this.t = t;
	}

	public java.lang.String getT() {
		return t;
	}

	private java.lang.String c_fix;

 	public void setC_fix(java.lang.String c_fix) {
		this.c_fix = c_fix;
	}

	public java.lang.String getC_fix() {
		return c_fix;
	}

	private java.lang.String lt_dts;

 	public void setLt_dts(java.lang.String lt_dts) {
		this.lt_dts = lt_dts;
	}

	public java.lang.String getLt_dts() {
		return lt_dts;
	}

	private java.lang.String s;

 	public void setS(java.lang.String s) {
		this.s = s;
	}

	public java.lang.String getS() {
		return s;
	}

	private java.lang.String l_cur;

 	public void setL_cur(java.lang.String l_cur) {
		this.l_cur = l_cur;
	}

	public java.lang.String getL_cur() {
		return l_cur;
	}

}